### PR TITLE
c: add support for structs

### PR DESCRIPTION
**Pull request by YerinAlexey**
### Description

This patch adds support for `struct`s in C generator.

### ToDo

- [x] Generate struct definition
- [x] Generate struct type (type annotations, nested structs)
- [x] Struct creation (`new User { ... }`)
- [x] Field access

### CODE REVIEW

**Comment by YerinAlexey** [comment]
Clippy test fails but this doesn't seem related to this PR

**Comment by garritfra** [comment]
@YerinAlexey it is. format!() needs a .into() in line 290.

**Comment by YerinAlexey** [comment]
> @YerinAlexey it is. format!() needs a .into() in line 290.

No, `format!()` already returns a `String`

**Comment by garritfra** [comment]
Are you sure? I thought it's &str, which is not owned.

**Comment by YerinAlexey** [comment]
https://doc.rust-lang.org/std/fmt/fn.format.html

**Comment by YerinAlexey** [comment]
I fixed clippy issues, they were caused because of a wrong `return` and using `format!("{{"}` instead of `String::from("{{")`

**Pull request merged**
